[build]
  command = "hugo && npm run build:functions"
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  HUGO_VERSION = "0.99.0"

[context.production.environment]
  HUGO_ENV = "production"
  NODE_ENV = "production"