[build]
  # command = "hugo && npm run build:functions" # Enable if using Netlify functions
  command = "hugo" # Disable if using the other command
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  HUGO_VERSION = "0.99.0"

[context.production.environment]
  HUGO_ENV = "production"
  NODE_ENV = "production"