name = "Hugo Liftoff"
license = "MIT"
licenselink = "https://github.com/wjh18/hugo-liftoff/blob/master/LICENSE"
description = "Minimal blog/portfolio theme with a focus on content creation and SEO best practices. An ideal choice for technical users jump-starting a personal brand."
homepage = "https://github.com/wjh18/hugo-liftoff"
demosite = "https://hugo-liftoff.netlify.app"
tags = ["blog", "portfolio", "personal", "responsive", "newsletter", "hero", "contact"]
features = []
[author]
    name = "Will J. Holmes"
    homepage = "https://www.wjholmes.com"