baseURL = 'https://www.example.com/'
languageCode = 'en-us'
title = 'Hugo Liftoff'
theme = 'hugo-liftoff'

# Enables disqus comments
# disqusShortname = ''

# Enables GA, enter your tracking ID
# googleAnalytics = ''

paginate = 5

[taxonomies]
    tag = "tags"
    category = "categories"
    # Enables series taxonomy
    series = "series"

[permalinks]
    # Removes `posts` from the permalink structure for nested subsections under `posts` section
    posts = "/:sections[last]/:slug/"

[params]

    # GTM tracking (leave blank to use GA)
    # gtm_id = ''

    # false for Universal Analytics, true for GA v4
    googleAnalyticsv4 = false

    # Disallows search engine crawling in robots.txt
    # disallow_search_engines = false

    # Default author for head meta
    author = 'John Doe'

    # Add a global meta description to head.html
    description = "Personal blog and portfolio site of John Joe."

    # Enable favicon, add files to {your-project}/static/*
    favicon = true

    # Customize newsletter text    
    newsletter_header = "This is my custom newsletter header with a captivating title."
    newsletter_description = "This is my custom newsletter description that tells you why you should sign up."
    newsletter_submit = "Join now"

    # Enable newsletter site-wide
    global_newsletter = true

    # Show a custom features project on homepage instead of latest project
    # Enter file name of the project
    # featured_project = 'this-is-my-project'

    # Customize footer text
    footer_text = "Built with Hugo Liftoff theme."

    # Debug template lookup in development
    debug = true

    # Custom avatar image
    # avatar = 'avatar.png'

    # Show social links in footer, home hero section, or about page
    footer_socials = true
    home_hero_socials = true
    about_page_socials = true

    # Adds Netlify identity JS to head
    netlify_cms = false

    # Add a label indicator next to the title of drafts in dev mode
    label_drafts = true

    # Enable or disable individual social icons
    social.links.twitter = "username"
    social.links.github = "username"
    social.links.stack_overflow = "1234567/username" # include user id
    # social.links.linkedin = "username"
    # social.links.email = "user@example.com"

    # Enable or disable individual social share icons
    social.share.facebook = true
    social.share.linkedin = true
    social.share.twitter = true
    social.share.reddit = true
    social.share.email = true


[markup]
  [markup.highlight]
    # Recommended syntax highlighting settings
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = 'monokai'
    tabWidth = 4


# Example menu configuration with nested subsections

[[menu.main]]
    identifier = "work"
    name = "Work"
    url = "/about"
    weight = 1

[[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    parent = "work"
    weight = 1

[[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects"
    parent = "work"
    weight = 1

[[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact"
    parent = "work"
    weight = 2

[[menu.main]]
    identifier = "writing"
    name = "Writing"
    url = "/posts"
    weight = 3

[[menu.main]]
    identifier = "posts"
    name = "All Posts"
    url = "/posts"
    parent = "writing"
    weight = 4

[[menu.main]]
    identifier = "guides"
    name = "Guides"
    url = "/posts/guides"
    parent = "writing"
    weight = 5

[[menu.main]]
    identifier = "resources"
    name = "Resources"
    url = "/posts/resources"
    parent = "writing"
    weight = 6

[[menu.main]]
    identifier = "thought"
    name = "Thoughts"
    url = "/posts/thoughts"
    parent = "writing"
    weight = 7

[[menu.main]]
    identifier = "explore"
    name = "Explore"
    url = "/categories"
    weight = 8

[[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories"
    parent = "explore"
    weight = 9

[[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags"
    parent = "explore"
    weight = 10

[[menu.main]]
    identifier = "series"
    name = "Series"
    url = "/series"
    parent = "explore"
    weight = 11